In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from analyzer import Analyzer
analyzer = Analyzer()

Analyzer opened

In [3]:
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns
from pypfopt.hierarchical_portfolio import HRPOpt

In [4]:
df_for_date = pd.read_csv('../csv_data/stocks/AAPL.csv')

df_pypfopt = pd.DataFrame(
    {
        'Date':df_for_date['Date']
    }
)

# df = pd.read_csv('../csv_data/stocks/AAPL.csv')

stock_lists = [
            'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'META', 'NVDA', 'NFLX', 'AMD',
            'DIS', 'BABA', 'V', 'JPM', 'JNJ', 'WMT', 'PG', 'MA', 'UNH', 'HD',
            'BAC', 'ADBE', 'CRM', 'PYPL', 'INTC', 'VZ', 'KO', 'PEP', 'T',
            'CSCO', 'XOM', 'ABT', 'TMO', 'ACN', 'TXN', 'QCOM', 'COST', 'SBUX',
            'MDT', 'LOW', 'HON', 'UPS', 'IBM', 'GS', 'CAT', 'MMM', 'SLB', 'SPY',
            'LLY', 'ASML', 'MU', 'CVX', 'NVS', 'PM', 'NVO', 'SHEL',
            'KLAC', 'PFE' ,'SPOT', 'BX', 'HOOD', 'GM', 'SE', 'TLT', 'SMH'        ]

for s in stock_lists:
    df = pd.read_csv('../csv_data/stocks/'+s+'.csv')
    df.rename(columns={'Close':s}, inplace=True)
    df_pypfopt = pd.merge(df_pypfopt, df[['Date', s]], on='Date', how='inner')

In [5]:
df_pypfopt.head()

,Date,AAPL,MSFT,GOOGL,AMZN,TSLA,META,NVDA,NFLX,AMD,...,SHEL,KLAC,PFE,SPOT,BX,HOOD,GM,SE,TLT,SMH
0,2021-10-20 00:00:00-04:00,145.583878,295.029755,140.432693,170.753006,288.600006,337.547089,22.006073,62.514000,116.389999,...,41.087818,31.531954,32.849895,251.179993,108.057930,41.830002,55.276054,360.600006,119.322807,129.287918
1,2021-10-21 00:00:00-04:00,145.798462,298.244843,140.548569,171.750504,298.000000,338.636597,22.592491,65.316002,119.330002,...,40.597485,31.958693,32.895950,255.000000,111.273903,41.279999,55.985336,363.299988,119.180641,130.762726
2,2021-10-22 00:00:00-04:00,145.027954,296.709229,136.269806,166.777496,303.226654,321.530426,22.626343,66.477997,119.820000,...,40.464527,32.675003,33.126202,252.960007,115.564621,39.590000,55.371899,355.299988,120.493225,129.608078
3,2021-10-25 00:00:00-04:00,144.979202,295.720825,136.151443,166.018494,341.619995,325.571777,23.064417,67.166000,122.360001,...,40.772015,32.694054,33.118526,257.890015,117.193604,39.009998,55.362309,348.320007,120.309319,130.263031
4,2021-10-26 00:00:00-04:00,145.642441,297.621033,137.995361,168.803497,339.476654,312.813965,24.608610,66.851997,122.930000,...,40.605801,32.574032,33.433208,252.199997,119.368362,39.570000,54.988510,343.570007,121.304077,131.005295

### 12 - 3 - 12
#### 12 months data train - 3 months data test - difference per test: 12 months

In [6]:
# # delta = 1 year (12 month), 1 array has difference of 3 months
start_end_dates = [
    ('2021-07-01', '2022-07-01'),
    ('2021-10-01', '2022-10-01'),
    ('2022-01-01', '2023-01-01'),
    ('2022-04-01', '2023-04-01'),
    ('2022-07-01', '2023-07-01'),
    ('2022-10-01', '2023-10-01'),
    ('2023-01-01', '2024-01-01'),
    ('2023-04-01', '2024-04-01'),
    ('2023-07-01', '2024-07-01'),
    ('2023-10-01', '2024-10-01'),
    ('2024-01-01', '2025-01-01'),
    ('2024-04-01', '2025-04-01'),
    ('2024-07-01', '2025-07-01'),
    ('2024-10-01', '2025-10-01'),
]

In [7]:
all_weight_data = {}

for (start_date, end_date) in start_end_dates:
    df_semester =  df_pypfopt[(df_pypfopt['Date'] >= start_date) & (df_pypfopt['Date'] <= end_date)].reset_index(drop=True)
    if 'Date' in df_semester.columns:
        df_semester.set_index('Date', inplace=True)
        
    mu = expected_returns.mean_historical_return(df_semester)
    S = risk_models.sample_cov(df_semester)
    
    # Optimize for maximal Sharpe ratio
    ef = EfficientFrontier(mu, S)
    ef.add_constraint(lambda x : x <= 0.20)
    weights = ef.max_sharpe(risk_free_rate=0.05)
    # print(weights)
    res = ef.portfolio_performance(risk_free_rate=0.05, verbose=True)
    expected_annual_return = str(float(res[0]) * 100)+'%'
    annual_volatility = str(float(res[1]) * 100)+'%'
    sharpe_ratio = float(res[2])

    weights_to_buy = {k:weights[k]*100 for k, v in sorted([(v,weights[v]*100) for k,v in enumerate(weights) if weights[v]>0], key=lambda x: x[1], reverse=True)}
    all_weight_data[start_date+'_'+end_date] = {
        'expected_annual_return' : expected_annual_return,
        'annual_volatility' : annual_volatility,
        'sharpe_ratio' : sharpe_ratio,
        'weights_to_buy': weights_to_buy
    }
    print('======')

Expected annual return: 45.5%
Annual volatility: 19.2%
Sharpe Ratio: 2.11
======
Expected annual return: 28.3%
Annual volatility: 19.3%
Sharpe Ratio: 1.21
======
Expected annual return: 48.9%
Annual volatility: 22.7%
Sharpe Ratio: 1.94
======
Expected annual return: 24.8%
Annual volatility: 17.7%
Sharpe Ratio: 1.12
======
Expected annual return: 92.6%
Annual volatility: 23.1%
Sharpe Ratio: 3.79
======
Expected annual return: 104.7%
Annual volatility: 19.3%
Sharpe Ratio: 5.18
======
Expected annual return: 130.1%
Annual volatility: 20.3%
Sharpe Ratio: 6.17
======
Expected annual return: 97.9%
Annual volatility: 14.4%
Sharpe Ratio: 6.45
======
Expected annual return: 78.2%
Annual volatility: 13.0%
Sharpe Ratio: 5.66
======
Expected annual return: 76.2%
Annual volatility: 11.1%
Sharpe Ratio: 6.39
======
Expected annual return: 93.3%
Annual volatility: 13.1%
Sharpe Ratio: 6.76
======
Expected annual return: 81.8%
Annual volatility: 13.4%
Sharpe Ratio: 5.72
======
Expected annual return: 113.2%
Annual volatility: 20.2%
Sharpe Ratio: 5.35
======
Expected annual return: 130.4%
Annual volatility: 18.8%
Sharpe Ratio: 6.68
======

In [8]:
all_weight_data

{'2021-07-01_2022-07-01': {'expected_annual_return': '45.50520454203638%',
  'annual_volatility': '19.19015426258591%',
  'sharpe_ratio': 2.1107284489634024,
  'weights_to_buy': {'KO': 20.0,
   'XOM': 20.0,
   'LLY': 20.0,
   'CVX': 20.0,
   'PFE': 16.205332488018538,
   'UNH': 3.79466751198151}},
 '2021-10-01_2022-10-01': {'expected_annual_return': '28.32605578319206%',
  'annual_volatility': '19.27470254786263%',
  'sharpe_ratio': 1.210190181937655,
  'weights_to_buy': {'UNH': 20.0,
   'XOM': 20.0,
   'LLY': 20.0,
   'CVX': 20.0,
   'KO': 17.88040829205897,
   'PFE': 1.23286760372992,
   'JNJ': 0.88672410421108}},
 '2022-01-01_2023-01-01': {'expected_annual_return': '48.91114768926181%',
  'annual_volatility': '22.68787995744659%',
  'sharpe_ratio': 1.9354451703562254,
  'weights_to_buy': {'XOM': 20.0,
   'LLY': 20.0,
   'CVX': 20.0,
   'NVO': 19.05829678733679,
   'SLB': 10.91613234730259,
   'KO': 5.9106916338841495,
   'PM': 4.11487923147648}},
 '2022-04-01_2023-04-01': {'expected_annual_return': '24.828825978953844%',
  'annual_volatility': '17.656931267516487%',
  'sharpe_ratio': 1.1230052197933738,
  'weights_to_buy': {'XOM': 20.0,
   'LLY': 20.0,
   'NVO': 20.0,
   'PEP': 17.6285296564594,
   'T': 15.55279067170118,
   'SBUX': 6.81867967183944}},
 '2022-07-01_2023-07-01': {'expected_annual_return': '92.5502223826415%',
  'annual_volatility': '23.093150070607905%',
  'sharpe_ratio': 3.791177128930199,
  'weights_to_buy': {'NVDA': 20.0,
   'NFLX': 20.0,
   'LLY': 20.0,
   'NVO': 19.60910475904197,
   'NVS': 9.95922417439938,
   'WMT': 8.926404504474709,
   'SLB': 1.50526656208393}},
 '2022-10-01_2023-10-01': {'expected_annual_return': '104.71241146499347%',
  'annual_volatility': '19.259305034200914%',
  'sharpe_ratio': 5.177362905251405,
  'weights_to_buy': {'NVDA': 20.0,
   'NVS': 20.0,
   'LLY': 19.835738377648852,
   'NVO': 16.6600186829953,
   'CAT': 11.879133736646,
   'META': 7.68116694983205,
   'SLB': 3.94394225287783}},
 '2023-01-01_2024-01-01': {'expected_annual_return': '130.07272064546765%',
  'annual_volatility': '20.255770295743602%',
  'sharpe_ratio': 6.174671158852425,
  'weights_to_buy': {'META': 20.0,
   'NVDA': 20.0,
   'LLY': 14.613630801678271,
   'SPOT': 12.40628019356604,
   'CRM': 8.08755158779221,
   'IBM': 6.12914307507298,
   'COST': 5.7453412087329,
   'NVO': 5.42857796452838,
   'NVS': 3.95537448209913,
   'SHEL': 2.90247746324323,
   'INTC': 0.7316232232868399}},
 '2023-04-01_2024-04-01': {'expected_annual_return': '97.94361206985222%',
  'annual_volatility': '14.41636500379118%',
  'sharpe_ratio': 6.447090653254834,
  'weights_to_buy': {'JPM': 20.0,
   'LLY': 20.0,
   'NVDA': 13.727289618341509,
   'IBM': 13.208171005068781,
   'WMT': 6.22306408034879,
   'META': 4.818656216139891,
   'HOOD': 4.36326282972629,
   'SPOT': 4.27942377678686,
   'MDT': 2.76105226621286,
   'MU': 2.6777308539462,
   'ABT': 2.25411017445833,
   'VZ': 1.8976685734961098,
   'COST': 1.79481003859847,
   'NFLX': 1.3957602475188,
   'UNH': 0.59900031935716}},
 '2023-07-01_2024-07-01': {'expected_annual_return': '78.24593736598588%',
  'annual_volatility': '12.951132996407965%',
  'sharpe_ratio': 5.655562133930742,
  'weights_to_buy': {'NVDA': 15.63556212294142,
   'LLY': 15.49055948547244,
   'T': 13.45110458431486,
   'COST': 13.117678047851369,
   'JPM': 12.88440449468978,
   'WMT': 9.24187231777069,
   'UNH': 4.06322353287391,
   'XOM': 3.93399240096962,
   'HOOD': 3.29321382942274,
   'MU': 3.1250057457266998,
   'SPOT': 2.78780049961697,
   'SHEL': 1.320651483501,
   'NVO': 1.277998022918,
   'IBM': 0.37693343193055}},
 '2023-10-01_2024-10-01': {'expected_annual_return': '76.17698899017562%',
  'annual_volatility': '11.137962181290737%',
  'sharpe_ratio': 6.390485784709961,
  'weights_to_buy': {'T': 20.0,
   'WMT': 16.207904184132342,
   'SPOT': 11.070309202986719,
   'MMM': 8.40136282168974,
   'PG': 8.126826363368691,
   'NVDA': 8.06593694079249,
   'JPM': 5.8134063850973705,
   'IBM': 5.60604054319791,
   'KO': 5.59462607053706,
   'PM': 3.1710028888305,
   'NFLX': 2.39142112728762,
   'HOOD': 2.18294166851258,
   'UNH': 1.18540345365303,
   'META': 0.68994727049916,
   'COST': 0.66240290773772,
   'SE': 0.61824239120544,
   'LLY': 0.21222578047168}},
 '2024-01-01_2025-01-01': {'expected_annual_return': '93.33948752076012%',
  'annual_volatility': '13.067994853785262%',
  'sharpe_ratio': 6.759987933050938,
  'weights_to_buy': {'WMT': 20.0,
   'T': 20.0,
   'SPOT': 13.431494755657319,
   'SE': 12.62466146576686,
   'PM': 7.79909060853317,
   'NVDA': 7.61384365945114,
   'PG': 7.12168067542049,
   'MMM': 4.70481110986598,
   'HOOD': 4.29478378838027,
   'NFLX': 1.83352582192619,
   'XOM': 0.57610811499862}},
 '2024-04-01_2025-04-01': {'expected_annual_return': '81.8293564731911%',
  'annual_volatility': '13.43901208520136%',
  'sharpe_ratio': 5.71689019893012,
  'weights_to_buy': {'T': 20.0,
   'PM': 20.0,
   'SE': 17.943557597926322,
   'MMM': 9.055699747204091,
   'SPOT': 8.980276015776251,
   'WMT': 8.06324083386383,
   'NVS': 5.50462628316203,
   'SHEL': 4.99242055537377,
   'BABA': 3.79055559913372,
   'AAPL': 1.09166415657592,
   'KO': 0.57795921098411}},
 '2024-07-01_2025-07-01': {'expected_annual_return': '113.24757798266563%',
  'annual_volatility': '20.24874464777951%',
  'sharpe_ratio': 5.345890812768786,
  'weights_to_buy': {'T': 20.0,
   'PM': 20.0,
   'HOOD': 14.5756322946955,
   'SPOT': 9.951639278686331,
   'TLT': 8.55525957160552,
   'IBM': 8.180732882231991,
   'SE': 8.17463491363479,
   'NFLX': 3.69309066153471,
   'ABT': 3.51111500128891,
   'JNJ': 3.3578953963223004}},
 '2024-10-01_2025-10-01': {'expected_annual_return': '130.3537007766361%',
  'annual_volatility': '18.756812505626257%',
  'sharpe_ratio': 6.683102512169124,
  'weights_to_buy': {'JNJ': 20.0,
   'T': 20.0,
   'HOOD': 20.0,
   'TLT': 17.098223571801167,
   'PM': 14.17596324784452,
   'GOOGL': 3.3010423016492796,
   'BABA': 2.7887543834027197,
   'NFLX': 1.04106330043916,
   'NVS': 0.8509679512558099,
   'VZ': 0.74398524360733}}}

## Backtest

In [9]:
from backtest import ManualBacktest
from datetime import datetime

In [10]:
backtest_months = 12

In [11]:
mb = ManualBacktest()

for a in all_weight_data:
    allocation = all_weight_data[a]['weights_to_buy']
    print('allocation : ')
    print(allocation)

    start_date_str = a.split('_')[1]
    start_date = datetime.strptime(start_date_str, '%Y-%m-%d')
    end_date = mb.delta_date(start_date, months = backtest_months)
    end_date_str = datetime.strftime(mb.delta_date(start_date, months = backtest_months), '%Y-%m-%d')

    print('start_date_str : ', start_date_str)
    print('end_date_str : ', end_date_str)

    df_port = mb.make_portfolio_rebalance(start_date_str, end_date_str, allocation)

    return_backtest = mb.calculate_return_df(df_port, start_date_str, end_date_str)
    std_backtest = mb.calculate_std_df(df_port, start_date_str, end_date_str)
    sharpe_ratio_backtest = return_backtest / std_backtest

    return_spy = mb.calculate_return_benchmark(start_date_str, end_date_str, 'SPY', 'Date')
    std_spy = mb.calculate_std_benchmark(start_date_str, end_date_str, 'SPY', 'Date')
    sharpe_ratio_spy = return_spy / std_spy
    
    return_1n = mb.calculate_return_1n(allocation, df_port)
    
    print('return_backtest : ', return_backtest)
    print('std_backtest : ', std_backtest)

    all_weight_data[a]['backtest'] = {}

    all_weight_data[a]['backtest']['start_date_backtest'] = start_date_str
    all_weight_data[a]['backtest']['end_date_backtest'] = str(end_date)[0:10]
    
    all_weight_data[a]['backtest']['pct_return_backtest'] = float(return_backtest)
    all_weight_data[a]['backtest']['std_backtest'] = float(std_backtest)
    all_weight_data[a]['backtest']['sharpe_ratio_backtest'] = float(sharpe_ratio_backtest)
    
    all_weight_data[a]['backtest']['pct_return_spy'] = float(return_spy)
    all_weight_data[a]['backtest']['std_spy'] = float(std_spy)
    all_weight_data[a]['backtest']['sharpe_ratio_spy'] = float(sharpe_ratio_spy)
    
    all_weight_data[a]['backtest']['pct_return_1n'] = float(return_1n)

    all_weight_data[a]['backtest']['pct_std_backtest'] = float(std_backtest)
    all_weight_data[a]['backtest']['high_water_mark'] = mb.high_water_mark
    all_weight_data[a]['backtest']['drawdown'] = mb.drawdown
    all_weight_data[a]['backtest']['stock_money_profit'] = mb.calculate_underperformed_stocks(allocation, df_port)

    print('all_weight_data[a] : ')
    print(all_weight_data[a])

    print('======')

allocation :
{'KO': 20.0, 'XOM': 20.0, 'LLY': 20.0, 'CVX': 20.0, 'PFE': 16.205332488018538, 'UNH': 3.79466751198151}
start_date_str :  2022-07-01
end_date_str :  2023-07-01
Total Money end :  111.45491570181719
Total Money start :  100.00000000000006
Total Money end :  425.9974365234375
Total Money start :  360.4895935058594
return_backtest :  11.454915701817123
std_backtest :  16.974254363586205
all_weight_data[a] :
{'expected_annual_return': '45.50520454203638%', 'annual_volatility': '19.19015426258591%', 'sharpe_ratio': 2.1107284489634024, 'weights_to_buy': {'KO': 20.0, 'XOM': 20.0, 'LLY': 20.0, 'CVX': 20.0, 'PFE': 16.205332488018538, 'UNH': 3.79466751198151}, 'backtest': {'start_date_backtest': '2022-07-01', 'end_date_backtest': '2023-07-01', 'pct_return_backtest': 11.454915701817123, 'std_backtest': 16.974254363586205, 'sharpe_ratio_backtest': 0.6748405824759307, 'pct_return_spy': 18.17190959120249, 'std_spy': 19.331596882496996, 'sharpe_ratio_spy': 0.9400107865716723, 'pct_return_1n': 7.898224212680649, 'pct_std_backtest': 16.974254363586205, 'high_water_mark': 114.18999135952392, 'drawdown': -12.014377918933523, 'stock_money_profit': {'PFE': -4.423611622729906, 'KO': -0.7310741940788184, 'UNH': -0.22039445464949514, 'CVX': 2.251473995861062, 'XOM': 5.347439009478357, 'LLY': 9.231082967935933}}}
======
allocation :
{'UNH': 20.0, 'XOM': 20.0, 'LLY': 20.0, 'CVX': 20.0, 'KO': 17.88040829205897, 'PFE': 1.23286760372992, 'JNJ': 0.88672410421108}
start_date_str :  2022-10-01
end_date_str :  2023-10-01
Total Money end :  123.1285956424117
Total Money start :  99.99999999999997
Total Money end :  412.2625732421875
Total Money start :  348.07989501953125
return_backtest :  23.12859564241173
std_backtest :  15.21248796932325
all_weight_data[a] :
{'expected_annual_return': '28.32605578319206%', 'annual_volatility': '19.27470254786263%', 'sharpe_ratio': 1.210190181937655, 'weights_to_buy': {'UNH': 20.0, 'XOM': 20.0, 'LLY': 20.0, 'CVX': 20.0, 'KO': 17.88040829205897, 'PFE': 1.23286760372992, 'JNJ': 0.88672410421108}, 'backtest': {'start_date_backtest': '2022-10-01', 'end_date_backtest': '2023-10-01', 'pct_return_backtest': 23.12859564241173, 'std_backtest': 15.21248796932325, 'sharpe_ratio_backtest': 1.5203690342468446, 'pct_return_spy': 18.439065036794172, 'std_spy': 16.784522367483923, 'sharpe_ratio_spy': 1.098575499086917, 'pct_return_1n': 13.374335962457874, 'pct_std_backtest': 15.21248796932325, 'high_water_mark': 126.64451394476606, 'drawdown': -11.360151069249465, 'stock_money_profit': {'PFE': -0.26905908467724715, 'UNH': -0.15118939568442968, 'JNJ': -0.016143051603137448, 'KO': 0.33023103706845447, 'CVX': 3.0368178265691768, 'XOM': 6.427893939233371, 'LLY': 13.77004437150552}}}
======
allocation :
{'XOM': 20.0, 'LLY': 20.0, 'CVX': 20.0, 'NVO': 19.05829678733679, 'SLB': 10.91613234730259, 'KO': 5.9106916338841495, 'PM': 4.11487923147648}
start_date_str :  2023-01-01
end_date_str :  2024-01-01
Total Money end :  119.63828251465449
Total Money start :  100.00000000000001
Total Money end :  460.2483825683594
Total Money start :  363.23199462890625
return_backtest :  19.638282514654477
std_backtest :  17.12626659271714
all_weight_data[a] :
{'expected_annual_return': '48.91114768926181%', 'annual_volatility': '22.68787995744659%', 'sharpe_ratio': 1.9354451703562254, 'weights_to_buy': {'XOM': 20.0, 'LLY': 20.0, 'CVX': 20.0, 'NVO': 19.05829678733679, 'SLB': 10.91613234730259, 'KO': 5.9106916338841495, 'PM': 4.11487923147648}, 'backtest': {'start_date_backtest': '2023-01-01', 'end_date_backtest': '2024-01-01', 'pct_return_backtest': 19.638282514654477, 'std_backtest': 17.12626659271714, 'sharpe_ratio_backtest': 1.1466762127249355, 'pct_return_spy': 26.709207716839295, 'std_spy': 13.013208844841284, 'sharpe_ratio_spy': 2.052468997869607, 'pct_return_1n': 14.012823602521474, 'pct_std_backtest': 17.12626659271714, 'high_water_mark': 126.01279949243221, 'drawdown': -10.509953551702257, 'stock_money_profit': {'CVX': -2.1805146500170878, 'XOM': -0.5851987404907, 'KO': -0.2028884016345982, 'PM': -0.0798870797830693, 'SLB': 0.3274743748598432, 'NVO': 10.102546562292371, 'LLY': 12.256750449427713}}}
======
allocation :
{'XOM': 20.0, 'LLY': 20.0, 'NVO': 20.0, 'PEP': 17.6285296564594, 'T': 15.55279067170118, 'SBUX': 6.81867967183944}
start_date_str :  2023-04-01
end_date_str :  2024-04-01
Total Money end :  135.24764685582386
Total Money start :  100.0
Total Money end :  507.1847534179687
Total Money start :  393.4664611816406
return_backtest :  35.24764685582386
std_backtest :  15.337200232095471
all_weight_data[a] :
{'expected_annual_return': '24.828825978953844%', 'annual_volatility': '17.656931267516487%', 'sharpe_ratio': 1.1230052197933738, 'weights_to_buy': {'XOM': 20.0, 'LLY': 20.0, 'NVO': 20.0, 'PEP': 17.6285296564594, 'T': 15.55279067170118, 'SBUX': 6.81867967183944}, 'backtest': {'start_date_backtest': '2023-04-01', 'end_date_backtest': '2024-04-01', 'pct_return_backtest': 35.24764685582386, 'std_backtest': 15.337200232095471, 'sharpe_ratio_backtest': 2.298180001723045, 'pct_return_spy': 28.901648159493558, 'std_spy': 11.374949339490742, 'sharpe_ratio_spy': 2.5408155497585265, 'pct_return_1n': 28.010966128740833, 'pct_std_backtest': 15.337200232095471, 'high_water_mark': 136.60887351290185, 'drawdown': -7.5635223028204885, 'stock_money_profit': {'SBUX': -0.7352697967080157, 'T': -0.5453900529504487, 'PEP': -0.4250002944337119, 'XOM': 0.8690679570977338, 'NVO': 12.352882745856242, 'LLY': 23.73135629696204}}}
======
allocation :
{'NVDA': 20.0, 'NFLX': 20.0, 'LLY': 20.0, 'NVO': 19.60910475904197, 'NVS': 9.95922417439938, 'WMT': 8.926404504474709, 'SLB': 1.50526656208393}
start_date_str :  2023-07-01
end_date_str :  2024-07-01
Total Money end :  189.46390584415502
Total Money start :  99.99999999999999
Total Money end :  531.408935546875
Total Money start :  426.4876403808594
return_backtest :  89.46390584415505
std_backtest :  20.807527842538544
all_weight_data[a] :
{'expected_annual_return': '92.5502223826415%', 'annual_volatility': '23.093150070607905%', 'sharpe_ratio': 3.791177128930199, 'weights_to_buy': {'NVDA': 20.0, 'NFLX': 20.0, 'LLY': 20.0, 'NVO': 19.60910475904197, 'NVS': 9.95922417439938, 'WMT': 8.926404504474709, 'SLB': 1.50526656208393}, 'backtest': {'start_date_backtest': '2023-07-01', 'end_date_backtest': '2024-07-01', 'pct_return_backtest': 89.46390584415505, 'std_backtest': 20.807527842538544, 'sharpe_ratio_backtest': 4.299593229968272, 'pct_return_spy': 24.601251063763407, 'std_spy': 11.080105629900322, 'sharpe_ratio_spy': 2.220308351336965, 'pct_return_1n': 66.8440536452662, 'pct_std_backtest': 20.807527842538544, 'high_water_mark': 192.96706683360577, 'drawdown': -10.113281140456145, 'stock_money_profit': {'SLB': -0.0578305152778551, 'NVS': 1.1897144215377047, 'WMT': 2.6585634448575046, 'NFLX': 10.518756127353022, 'NVO': 16.594134815315854, 'LLY': 19.92891114867887, 'NVDA': 38.63165640168989}}}
======
allocation :
{'NVDA': 20.0, 'NVS': 20.0, 'LLY': 19.835738377648852, 'NVO': 16.6600186829953, 'CAT': 11.879133736646, 'META': 7.68116694983205, 'SLB': 3.94394225287783}
start_date_str :  2023-10-01
end_date_str :  2024-10-01
Total Money end :  165.0866162895017
Total Money start :  100.00000000000003
Total Money end :  555.793701171875
Total Money start :  412.0986328125
return_backtest :  65.08661628950165
std_backtest :  23.63782374634093
all_weight_data[a] :
{'expected_annual_return': '104.71241146499347%', 'annual_volatility': '19.259305034200914%', 'sharpe_ratio': 5.177362905251405, 'weights_to_buy': {'NVDA': 20.0, 'NVS': 20.0, 'LLY': 19.835738377648852, 'NVO': 16.6600186829953, 'CAT': 11.879133736646, 'META': 7.68116694983205, 'SLB': 3.94394225287783}, 'backtest': {'start_date_backtest': '2023-10-01', 'end_date_backtest': '2024-10-01', 'pct_return_backtest': 65.08661628950165, 'std_backtest': 23.63782374634093, 'sharpe_ratio_backtest': 2.75349444127981, 'pct_return_spy': 34.86909611387974, 'std_spy': 12.463876276133531, 'sharpe_ratio_spy': 2.7976125036357167, 'pct_return_1n': 55.06118825513238, 'pct_std_backtest': 23.63782374634093, 'high_water_mark': 174.74693165503015, 'drawdown': -15.860305186659623, 'stock_money_profit': {'SLB': -0.9379750067414863, 'NVS': 3.415762826945567, 'NVO': 4.991892329813016, 'CAT': 5.5779665184862885, 'META': 6.794080408593322, 'LLY': 12.97594191705602, 'NVDA': 32.26894729534896}}}
======
allocation :
{'META': 20.0, 'NVDA': 20.0, 'LLY': 14.613630801678271, 'SPOT': 12.40628019356604, 'CRM': 8.08755158779221, 'IBM': 6.12914307507298, 'COST': 5.7453412087329, 'NVO': 5.42857796452838, 'NVS': 3.95537448209913, 'SHEL': 2.90247746324323, 'INTC': 0.7316232232868399}
start_date_str :  2024-01-01
end_date_str :  2025-01-01
Total Money end :  177.45291193226603
Total Money start :  99.99999999999997
Total Money end :  574.7879028320312
Total Money start :  457.6726989746094
return_backtest :  77.45291193226609
std_backtest :  25.369083497818487
all_weight_data[a] :
{'expected_annual_return': '130.07272064546765%', 'annual_volatility': '20.255770295743602%', 'sharpe_ratio': 6.174671158852425, 'weights_to_buy': {'META': 20.0, 'NVDA': 20.0, 'LLY': 14.613630801678271, 'SPOT': 12.40628019356604, 'CRM': 8.08755158779221, 'IBM': 6.12914307507298, 'COST': 5.7453412087329, 'NVO': 5.42857796452838, 'NVS': 3.95537448209913, 'SHEL': 2.90247746324323, 'INTC': 0.7316232232868399}, 'backtest': {'start_date_backtest': '2024-01-01', 'end_date_backtest': '2025-01-01', 'pct_return_backtest': 77.45291193226609, 'std_backtest': 25.369083497818487, 'sharpe_ratio_backtest': 3.0530433603928318, 'pct_return_spy': 25.589292111985724, 'std_spy': 12.55198169377708, 'sharpe_ratio_spy': 2.038665506074804, 'pct_return_1n': 41.57684849059524, 'pct_std_backtest': 25.369083497818487, 'high_water_mark': 192.38673678266838, 'drawdown': -13.49436151484657, 'stock_money_profit': {'NVO': -0.8051737814777464, 'INTC': -0.42062935682797736, 'SHEL': -0.030116979299462887, 'NVS': -0.000396363016697876, 'COST': 2.3927192847931638, 'IBM': 2.5152950784518637, 'CRM': 2.5282040688355405, 'LLY': 4.561232218661905, 'META': 13.945343692082474, 'SPOT': 16.99160965738669, 'NVDA': 35.774824412676296}}}
======
allocation :
{'JPM': 20.0, 'LLY': 20.0, 'NVDA': 13.727289618341509, 'IBM': 13.208171005068781, 'WMT': 6.22306408034879, 'META': 4.818656216139891, 'HOOD': 4.36326282972629, 'SPOT': 4.27942377678686, 'MDT': 2.76105226621286, 'MU': 2.6777308539462, 'ABT': 2.25411017445833, 'VZ': 1.8976685734961098, 'COST': 1.79481003859847, 'NFLX': 1.3957602475188, 'UNH': 0.59900031935716}
start_date_str :  2024-04-01
end_date_str :  2025-04-01
Total Money end :  129.38234735776066
Total Money start :  100.00000000000004
Total Money end :  551.8167724609375
Total Money start :  507.1847534179687
return_backtest :  29.382347357760608
std_backtest :  20.4934066284664
all_weight_data[a] :
{'expected_annual_return': '97.94361206985222%', 'annual_volatility': '14.41636500379118%', 'sharpe_ratio': 6.447090653254834, 'weights_to_buy': {'JPM': 20.0, 'LLY': 20.0, 'NVDA': 13.727289618341509, 'IBM': 13.208171005068781, 'WMT': 6.22306408034879, 'META': 4.818656216139891, 'HOOD': 4.36326282972629, 'SPOT': 4.27942377678686, 'MDT': 2.76105226621286, 'MU': 2.6777308539462, 'ABT': 2.25411017445833, 'VZ': 1.8976685734961098, 'COST': 1.79481003859847, 'NFLX': 1.3957602475188, 'UNH': 0.59900031935716}, 'backtest': {'start_date_backtest': '2024-04-01', 'end_date_backtest': '2025-04-01', 'pct_return_backtest': 29.382347357760608, 'std_backtest': 20.4934066284664, 'sharpe_ratio_backtest': 1.433746369768851, 'pct_return_spy': 8.799952826300313, 'std_spy': 13.881940060671871, 'sharpe_ratio_spy': 0.6339137604570816, 'pct_return_1n': 32.51985504637076, 'pct_std_backtest': 20.4934066284664, 'high_water_mark': 149.27980867415008, 'drawdown': -15.819342384592918, 'stock_money_profit': {'MU': -0.7578878238819731, 'UNH': 0.05111224941724757, 'MDT': 0.14151751505771104, 'VZ': 0.2766930366920535, 'ABT': 0.4481219823056115, 'COST': 0.5932201962622263, 'NFLX': 0.7135914933958867, 'META': 0.9491954106245766, 'LLY': 1.3125125094402392, 'NVDA': 3.0113965312622852, 'WMT': 3.0944837213738765, 'SPOT': 4.58251542559613, 'IBM': 4.7959943019454485, 'JPM': 5.055804035645959, 'HOOD': 5.1140767726233545}}}
======
allocation :
{'NVDA': 15.63556212294142, 'LLY': 15.49055948547244, 'T': 13.45110458431486, 'COST': 13.117678047851369, 'JPM': 12.88440449468978, 'WMT': 9.24187231777069, 'UNH': 4.06322353287391, 'XOM': 3.93399240096962, 'HOOD': 3.29321382942274, 'MU': 3.1250057457266998, 'SPOT': 2.78780049961697, 'SHEL': 1.320651483501, 'NVO': 1.277998022918, 'IBM': 0.37693343193055}
start_date_str :  2024-07-01
end_date_str :  2025-07-01
Total Money end :  133.51784917022013
Total Money start :  100.00000000000003
Total Money end :  609.3681030273438
Total Money start :  531.408935546875
return_backtest :  33.517849170220096
std_backtest :  20.95095416934764
all_weight_data[a] :
{'expected_annual_return': '78.24593736598588%', 'annual_volatility': '12.951132996407965%', 'sharpe_ratio': 5.655562133930742, 'weights_to_buy': {'NVDA': 15.63556212294142, 'LLY': 15.49055948547244, 'T': 13.45110458431486, 'COST': 13.117678047851369, 'JPM': 12.88440449468978, 'WMT': 9.24187231777069, 'UNH': 4.06322353287391, 'XOM': 3.93399240096962, 'HOOD': 3.29321382942274, 'MU': 3.1250057457266998, 'SPOT': 2.78780049961697, 'SHEL': 1.320651483501, 'NVO': 1.277998022918, 'IBM': 0.37693343193055}, 'backtest': {'start_date_backtest': '2024-07-01', 'end_date_backtest': '2025-07-01', 'pct_return_backtest': 33.517849170220096, 'std_backtest': 20.95095416934764, 'sharpe_ratio_backtest': 1.5998244709665057, 'pct_return_spy': 14.670277871831544, 'std_spy': 20.475466739652063, 'sharpe_ratio_spy': 0.7164807551576641, 'pct_return_1n': 42.36323264931878, 'pct_std_backtest': 20.95095416934764, 'high_water_mark': 134.64124137778555, 'drawdown': -18.09960706312684, 'stock_money_profit': {'LLY': -2.2558901257810877, 'UNH': -1.3336123811210028, 'NVO': -0.652175984663945, 'MU': -0.23933504707778308, 'XOM': -0.06539154168980765, 'SHEL': 0.023989067652934404, 'IBM': 0.2689070388802874, 'COST': 2.255191081390876, 'SPOT': 3.6287418351232237, 'NVDA': 3.6539724900129134, 'WMT': 4.350970023573099, 'JPM': 5.750489315296091, 'T': 8.0832841615371, 'HOOD': 10.048709237087166}}}
======
allocation :
{'T': 20.0, 'WMT': 16.207904184132342, 'SPOT': 11.070309202986719, 'MMM': 8.40136282168974, 'PG': 8.126826363368691, 'NVDA': 8.06593694079249, 'JPM': 5.8134063850973705, 'IBM': 5.60604054319791, 'KO': 5.59462607053706, 'PM': 3.1710028888305, 'NFLX': 2.39142112728762, 'HOOD': 2.18294166851258, 'UNH': 1.18540345365303, 'META': 0.68994727049916, 'COST': 0.66240290773772, 'SE': 0.61824239120544, 'LLY': 0.21222578047168}
start_date_str :  2024-10-01
end_date_str :  2025-10-01
Total Money end :  144.66761841545417
Total Money start :  100.00000000000004
Total Money end :  661.3153076171875
Total Money start :  555.793701171875
return_backtest :  44.66761841545411
std_backtest :  18.10405238890706
all_weight_data[a] :
{'expected_annual_return': '76.17698899017562%', 'annual_volatility': '11.137962181290737%', 'sharpe_ratio': 6.390485784709961, 'weights_to_buy': {'T': 20.0, 'WMT': 16.207904184132342, 'SPOT': 11.070309202986719, 'MMM': 8.40136282168974, 'PG': 8.126826363368691, 'NVDA': 8.06593694079249, 'JPM': 5.8134063850973705, 'IBM': 5.60604054319791, 'KO': 5.59462607053706, 'PM': 3.1710028888305, 'NFLX': 2.39142112728762, 'HOOD': 2.18294166851258, 'UNH': 1.18540345365303, 'META': 0.68994727049916, 'COST': 0.66240290773772, 'SE': 0.61824239120544, 'LLY': 0.21222578047168}, 'backtest': {'start_date_backtest': '2024-10-01', 'end_date_backtest': '2025-10-01', 'pct_return_backtest': 44.66761841545411, 'std_backtest': 18.10405238890706, 'sharpe_ratio_backtest': 2.46727182709786, 'pct_return_spy': 18.985750688218168, 'std_spy': 19.386618066131557, 'sharpe_ratio_spy': 0.9793224699353981, 'pct_return_1n': 58.34916686550624, 'pct_std_backtest': 18.10405238890706, 'high_water_mark': 145.88424563921265, 'drawdown': -14.925929960320344, 'stock_money_profit': {'PG': -0.7508224047042198, 'UNH': -0.46222459270750527, 'KO': -0.22792561555316393, 'LLY': -0.01265649829881585, 'COST': 0.03372306880191056, 'META': 0.1712995778672709, 'SE': 0.5359918553111835, 'PM': 1.1761423156947166, 'MMM': 1.3514097350054062, 'NFLX': 1.5740171794121545, 'IBM': 1.922797445194126, 'JPM': 3.106827675529116, 'WMT': 4.32452906432588, 'NVDA': 4.8460223462749, 'T': 6.067044238472057, 'SPOT': 9.592302137934801, 'HOOD': 11.419140886894276}}}
======
allocation :
{'WMT': 20.0, 'T': 20.0, 'SPOT': 13.431494755657319, 'SE': 12.62466146576686, 'PM': 7.79909060853317, 'NVDA': 7.61384365945114, 'PG': 7.12168067542049, 'MMM': 4.70481110986598, 'HOOD': 4.29478378838027, 'NFLX': 1.83352582192619, 'XOM': 0.57610811499862}
start_date_str :  2025-01-01
end_date_str :  2026-01-01
Total Money end :  128.2433251524495
Total Money start :  100.00000000000003
Total Money end :  676.635009765625
Total Money start :  573.3756713867188
return_backtest :  28.243325152449465
std_backtest :  20.13281624107459
all_weight_data[a] :
{'expected_annual_return': '93.33948752076012%', 'annual_volatility': '13.067994853785262%', 'sharpe_ratio': 6.759987933050938, 'weights_to_buy': {'WMT': 20.0, 'T': 20.0, 'SPOT': 13.431494755657319, 'SE': 12.62466146576686, 'PM': 7.79909060853317, 'NVDA': 7.61384365945114, 'PG': 7.12168067542049, 'MMM': 4.70481110986598, 'HOOD': 4.29478378838027, 'NFLX': 1.83352582192619, 'XOM': 0.57610811499862}, 'backtest': {'start_date_backtest': '2025-01-01', 'end_date_backtest': '2026-01-01', 'pct_return_backtest': 28.243325152449465, 'std_backtest': 20.13281624107459, 'sharpe_ratio_backtest': 1.4028501931502244, 'pct_return_spy': 18.009019833222396, 'std_spy': 19.406638247904297, 'sharpe_ratio_spy': 0.9279824564755399, 'pct_return_1n': 34.75559725423114, 'pct_std_backtest': 20.13281624107459, 'high_water_mark': 143.93175442818716, 'drawdown': -15.504940324175173, 'stock_money_profit': {'PG': -0.8102405188875768, 'XOM': 0.09366457522920635, 'NFLX': 0.10518598127680612, 'MMM': 1.2123938290264826, 'NVDA': 2.6556263707053986, 'SE': 2.7327144964229397, 'T': 2.735649326622145, 'PM': 2.895972808150301, 'SPOT': 3.606455983973124, 'WMT': 4.994761726601059, 'HOOD': 8.021140573329589}}}
======
allocation :
{'T': 20.0, 'PM': 20.0, 'SE': 17.943557597926322, 'MMM': 9.055699747204091, 'SPOT': 8.980276015776251, 'WMT': 8.06324083386383, 'NVS': 5.50462628316203, 'SHEL': 4.99242055537377, 'BABA': 3.79055559913372, 'AAPL': 1.09166415657592, 'KO': 0.57795921098411}
start_date_str :  2025-04-01
end_date_str :  2026-04-01
Total Money end :  100.68172746496043
Total Money start :  100.00000000000004
Total Money end :  651.9373779296875
Total Money start :  551.8167724609375
return_backtest :  0.6817274649603885
std_backtest :  17.308513707039605
all_weight_data[a] :

In [12]:
mean_backtest = []
std_backtest = []
sr_backtest = []
mean_spy = []
std_spy = []
sr_spy = []

for a in all_weight_data:
    mean_backtest.append(all_weight_data[a]['backtest']['pct_return_backtest'])
    std_backtest.append(all_weight_data[a]['backtest']['std_backtest'])
    sr_backtest.append(all_weight_data[a]['backtest']['sharpe_ratio_backtest'])

    mean_spy.append(all_weight_data[a]['backtest']['pct_return_spy'])
    std_spy.append(all_weight_data[a]['backtest']['std_spy'])
    sr_spy.append(all_weight_data[a]['backtest']['sharpe_ratio_spy'])

In [13]:
print('backtest MVO: ')
print('mean : ', np.mean(mean_backtest))
print('std : ', np.mean(std_backtest))
print('sr : ', np.mean(sr_backtest))

backtest MVO:
mean :  32.43162785645742
std :  18.751724312174616
sr :  1.6071698504621157

In [14]:
print('SPY: ')
print('mean : ', np.mean(mean_spy))
print('std : ', np.mean(std_spy))
print('sr : ', np.mean(sr_spy))

SPY:
mean :  20.96396283639609
std :  15.308588543891249
sr :  1.4896867869982864

In [15]:
px = analyzer.prepare_price_panel(df_pypfopt)
wf = analyzer.walk_forward(px, first_rebalance='2022-07-01', train_years=1, freq='QS',
                           max_weight=0.20, risk_free_rate=0.05, cost_bps=20, benchmark='SPY')

rf_eval = 0.05
wf_summary = pd.DataFrame({
    'MVO gross': analyzer.performance_summary(wf['mvo_gross'], rf_eval),
    'MVO net 20 bps': analyzer.performance_summary(wf['mvo_net'], rf_eval),
    'SPY': analyzer.performance_summary(wf['benchmark'], rf_eval),
    '1/N same universe': analyzer.performance_summary(wf['equal_weight'], rf_eval)
}).T

print('out-of-sample : ', wf['mvo_gross'].index[0].date(), 'to', wf['mvo_gross'].index[-1].date())
print('average in-sample (optimizer) sharpe : ', round(float(np.mean(wf['in_sample_sharpe'])), 2))
wf_summary

out-of-sample :  2022-07-05 to 2026-10-16
average in-sample (optimizer) sharpe :  5.32

,cagr,volatility,sharpe_ratio,max_drawdown,growth_of_1
MVO gross,0.438156,0.200452,1.664515,-0.166275,4.671141
MVO net 20 bps,0.428126,0.200580,1.628644,-0.167445,4.534506
SPY,0.187771,0.160818,0.839453,-0.188235,2.075013
1/N same universe,0.233118,0.163392,1.058418,-0.195224,2.432466